// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUrlShortenerServiceServer is an autogenerated mock type for the UnsafeUrlShortenerServiceServer type
type UnsafeUrlShortenerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUrlShortenerServiceServer provides a mock function with given fields:
func (_m *UnsafeUrlShortenerServiceServer) mustEmbedUnimplementedUrlShortenerServiceServer() {
	_m.Called()
}

// NewUnsafeUrlShortenerServiceServer creates a new instance of UnsafeUrlShortenerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeUrlShortenerServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeUrlShortenerServiceServer {
	mock := &UnsafeUrlShortenerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
