// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UrlShortenerHadler is an autogenerated mock type for the UrlShortenerHadler type
type UrlShortenerHadler struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: w, r
func (_m *UrlShortenerHadler) Resolve(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Shorten provides a mock function with given fields: w, r
func (_m *UrlShortenerHadler) Shorten(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewUrlShortenerHadler creates a new instance of UrlShortenerHadler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlShortenerHadler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlShortenerHadler {
	mock := &UrlShortenerHadler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
